# Generated by Django 2.2.6 on 2019-10-19 11:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imageDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('dateTime', models.DateTimeField(default=datetime.datetime(2019, 10, 19, 11, 59, 19, 412666, tzinfo=utc))),
                ('sourceUrl', models.TextField()),
                ('imageUrl', models.TextField()),
            ],
        ),
    ]
