# Generated by Django 2.2.6 on 2019-10-19 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedb',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 12, 22, 21, 226871, tzinfo=utc)),
        ),
    ]
