# Generated by Django 2.2.6 on 2019-10-19 12:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191019_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedb',
            name='label',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagedb',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 12, 29, 4, 884974, tzinfo=utc)),
        ),
    ]
