# Generated by Django 2.2.6 on 2019-10-19 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191019_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedb',
            name='icon',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagedb',
            name='title',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textdb',
            name='icon',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textdb',
            name='title',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagedb',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 19, 1, 10, 655836, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='textdb',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 19, 1, 10, 700921, tzinfo=utc)),
        ),
    ]
